### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets

### ISSUE THREAD

**Issue by dazman90** [zeldamods/event-editor#1]
Hey im a windows user trying to get this tool to work for me has been a headache so far but  none the less I am greatfull for your contribution to the modding comunity.
Anyway when I run the command
`py -3.7 -m eventeditor`
it throws the error
`ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets`
and when I atempt to install that by running `py -m pip install PyQt5.QtWebEngineWidgets`
this error gets throne
`  Could not find a version that satisfies the requirement PyQt5.QtWebEngineWidgets (from versions: )
No matching distribution found for PyQt5.QtWebEngineWidgets`
I am quite new to python software so I realy dont know how to fix this...
Thanks, dazman

**Comment by leoetlino** [comment]
Sorry for the delay; it looks like one day I accidentally marked a GitHub email as spam and I haven't been receiving any notification since...

Please refer to this page for setup instructions:

https://zeldamods.org/wiki/Help:Tools/EventEditor

It looks like the PyQt devs moved the WebEngine stuff to a separate package, which you need to install with `py -m pip install PyQtWebEngine`.

**Comment by paulsybrandy** [comment]
@leoetlino thanks for that information. It did install with that command. However, when I try running the original command that caused the error, it still comes up with, "ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'"

I know this is an old issue thread but hoping someone can shed some light on this for me. Thanks.

**Comment by leoetlino** [comment]
Hmm, that's weird. Try uninstalling PyQtWebEngine (`py -m pip uninstall PyQtWebEngine`) and then installing it again?

**Comment by paulsybrandy** [comment]
@leoetlino, I did as requested, but the same error message comes up after reinstalling.

**Comment by paulsybrandy** [comment]
@leoetlino, I did as requested, but the same error message comes up after reinstalling.
