### ISSUE TITLE
"AttributeError: cython_sources"

### ISSUE THREAD

**Issue by miraclematters** [zeldamods/event-editor#13]
I cannot install eventeditor due to this error.

output:
[Output.txt](https://github.com/zeldamods/event-editor/files/13722101/Output.txt)

**Comment by VillainousSsnake** [comment]
Use Python 3.11.7 and see if it works. If that doesn’t work use the latest version of Python 3.8

**Comment by leoetlino** [comment]
Should be fixed by 1.3.9-1
