### ISSUE TITLE
I am unable to export to text 

### ISSUE THREAD

**Issue by cualquiercosa327** [zeldamods/event-editor#3]
Hello,i am trying to export to plain text the event files from 1 2 switch but i am unable.
I dont know if the fact the files are .bin files are related.
i have uploaded the files
Thank you
[Eventos.zip](https://github.com/zeldamods/event-editor/files/3808868/Eventos.zip)

**Comment by leoetlino** [comment]
The event flowcharts load fine for me. What issue are you having more precisely?

**Comment by cualquiercosa327** [comment]
Hello,i am unable to make the program run.I installed as the README said,everything is fine
but i am unable to launch it.
i tried a lot of stuff ,as some python websites explained,but nothing.
I also tried create an executable with py2exe but again failed.
thank you

**Comment by leoetlino** [comment]
So you're on Windows? Have you tried installing the `PyQt5` and `PyQtWebEngine` package? Also, make sure you have **64-bit** Python 3.**6**+

**Comment by cualquiercosa327** [comment]
[setup.zip](https://github.com/zeldamods/event-editor/files/3819314/setup.zip)

Hello,i have just try again and it worked. I had installed the latest python i found ,if my memory doesnt fail it was a 3.8.
Now i start again with windows sandbox , i installed python-3.6.2-amd64  and once it finish : 
>python -m pip install PyQt5
>python -m pip install PyQtWebEngine
>python -m pip install eventeditor

and it works great with flowchart but it was no show anything with the file from timeline directory which use the same file format .


Other question : i have tried to use py2exe to create a directory with everything and could use without need to install python , i paste a setup.py from a website 

I tried to mod it but i dont know why.i attach the latest try (I know there are no any eventeditor.py file.I put the _main_ and others from the directory,but no success)
Thank you for everything

**Comment by leoetlino** [comment]
Sorry, I have no idea, I don't use Windows nor py2exe. Maybe you need to add PyQt5 and PyQtWebEngine as dependencies to setup.py?

**Comment by cualquiercosa327** [comment]
Hello,i have no know about python but if you want i can try.how could i chat with you directly?

Other question,did you test the file Kazuate.bfevfl from timeline? It doesnt work with your program
Thanks

**Comment by leoetlino** [comment]
https://discordapp.com/invite/KXUyw6c

Yeah, event timelines are not supported by EventEditor yet. Only flowcharts can be edited in EventEditor.
