### ISSUE TITLE
Use oead instead of syaz0?

### ISSUE THREAD

**Issue by zardini123** [zeldamods/event-editor#5]
I tried installing event-editor using pip3 and the dependency syaz0 failed to build on my macOS system.  I did some research and I found that syaz0 is deprecated in replacement for oead.

Would switching to oead be possible being that it's the package that is in active development?

**Comment by leoetlino** [comment]
Good idea, I've replaced syaz0 with oead.

**Comment by zardini123** [comment]
For some reason when I run ```pip install eventeditor``` it still tries installing syaz0 as a dependency.  It installs oead, but syaz0 too.  I tried running the install command with option ```--no-cache-dir``` to ensure that it wasn't due to caching, but the option changes nothing about dependency listing.  Any idea what's happening?

```
Collecting syaz0~=1.0
  Downloading syaz0-1.0.1.tar.gz (704 kB)
     |████████████████████████████████| 704 kB 2.6 MB/s 
Requirement already satisfied: sortedcontainers~=2.0 in /usr/local/lib/python3.8/site-packages (from byml~=2.0->eventeditor) (2.2.2)
Building wheels for collected packages: PyYAML, syaz0
  Building wheel for PyYAML (setup.py) ... done
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp38-cp38-macosx_10_14_x86_64.whl size=44624 sha256=680137f9a266c9e720af178f7df6de41e0952fe96589549eb1f68e5fe93a61e7
  Stored in directory: /private/var/folders/bp/899_7hrs2kdcds0r7bw7s96c0000gn/T/pip-ephem-wheel-cache-irij2ht8/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
  Building wheel for syaz0 (setup.py) ... error
```

**Comment by leoetlino** [comment]
Looks like that's because byml-v2 is still using syaz0. I've released a new version of byml-v2 that uses oead instead of syaz0 for Yaz0 compression; can you try again?

**Comment by zardini123** [comment]
Yep, works now!  Thank you very much!  Now I am able to use event editor!
