### ISSUE TITLE
Flowchart shows nothing

### ISSUE THREAD

**Issue by slyrp** [zeldamods/event-editor#7]
I know this is pretty old, but after installing all Qt5 dll's to System32 from multiple sources in my drive including the official PyQt5 module, I am unable to view the flowchart. This makes me have to resort to using the "Export graph data to JSON" and even then I do not know how to turn it back into an bfevfl file so any help would greatly appreciated.

**Comment by leoetlino** [comment]
That doesn't sound good. What version of Windows are you using? 32 or 64 bit? What version of Python?

Have you tried launching EventEditor from the command line and watching for error messages in the console output?

**Comment by slyrp** [comment]
64 bit, I'm using 3.10.4. EventEditor shows no visible errors, it did when there wasn't Qt5 dll's installed in System32 but that's it. I don't think they are corrupt because they came directly from the module and I upgraded it to make sure. I've also upgraded all modules that EventEditor uses but to no avail. I'm not sure what to do really, I'll try some other things and tell you if it works.

Edit: Windows 10 Build 19043.1826

**Comment by slyrp** [comment]
Ok issue solved, I might sound stupid was I was running __main__.py instead of eventeditor.exe. I see that you are very active and help people very frequently so thank you so much for that.

**Comment by ForsakenHarmony** [comment]
Hmm, seems I'm having the same issue I just get a blank window, I'm running via the `.exe` that's added to the `PATH`

```
Python 3.10.9
pip 23.1.2
```

**Comment by leoetlino** [comment]
https://stackoverflow.com/questions/59987649/qwebengineview-not-showing-anything-on-windows-10

Does setting QTWEBENGINE_DISABLE_SANDBOX (as explained in the post) fix your issue?

**Comment by ForsakenHarmony** [comment]
@leoetlino that does seem to fix it, weird

It's installed on my `C:\` drive same as my OS

**Comment by leoetlino** [comment]
Yeah that's a bit odd. Doesn't sound like the same issue as the one sllyrp was having.
