### ISSUE TITLE
Unable to open some files form TOTK

### ISSUE THREAD

**Issue by MediaMoots** [zeldamods/event-editor#9]
These event flow's and others don't load when opening them in 1.3.6
[Events.zip](https://github.com/zeldamods/event-editor/files/11932337/Events.zip)

**Comment by ArchLeaders** [comment]
Those are timeline files, eventeditor only supports flowcharts.

You can use this tool to view timeline files as JSON if you want.
https://github.com/ArchLeaders/EvflToJson

**Comment by MediaMoots** [comment]
Ok thank you!
